multiple fixes and second argument added for connect and ap

diff --git a/qw b/qw
--- a/qw
+++ b/qw
@@ -2,10 +2,12 @@
 
 # global variables
 me=`basename $0`
-version="0.1"
+version="0.2"
 
 ap_file="/tmp/qw_ap.conf"
 dhcp_file="/tmp/qw_dhcp.conf"
+dhcp_pidfile="/tmp/qw_dhcp.pid"
+dhclient_pidfile="/tmp/qw_dhclient.pid"
 wpa_file="/tmp/qw_wpa.conf"
 
 ssid="quickAP"
@@ -18,12 +20,11 @@ print_usage(){
 Usage: $me command
 
 commands:
-   ap               start configured ap
-   connect          connect to configured ap
-   sniff [channel]  switch to monitor mode
+   ap [ssid]        start configured ap
+   connect [ssid]   connect to configured ap
+   sniff [channel]  start sniffing in monitor mode
    managed          switch to managed mode
-   up               put interface up
-   down             stop everything and put interface down
+   kill             kill everything and put interface down
    random           set random mac
    permanent        reset permanent mac
 
@@ -39,6 +40,7 @@ kill_all(){
     killall -q hostapd
     killall -q wpa_supplicant
     killall -q dhclient
+    set_interface_down
 }
 
 
@@ -50,7 +52,6 @@ set_interface_up(){
 
 
 set_interface_down(){
-    kill_all
     ip l s $wlan_iface down
 }
 
@@ -68,16 +69,23 @@ set_monitor_mode(){
     type airodump-ng >/dev/null 2>&1 || { echo >&2 "Error: airodump-ng is required."; exit 1; }
     set_interface_down
     iw $wlan_iface set type monitor
-    ip l s $wlan_iface up
+    set_interface_up
+    if [ $arg2 ]
+    then
+        channel="-c $arg2"
+    fi
     airodump-ng $wlan_iface $channel
 }
 
 
 
 stop_ap(){
-    kill_all
+    kill `cat $dhcp_pidfile`
     echo $old_forward_value > /proc/sys/net/ipv4/ip_forward
-    iptables -t nat -D POSTROUTING -o $out_iface -j MASQUERADE
+    if [ $out_iface ] && [ $wlan_iface != $out_iface ]
+    then
+        iptables -t nat -D POSTROUTING -o $out_iface -j MASQUERADE
+    fi
     ip a d 10.113.119.1/24 dev $wlan_iface
     rm $ap_file
     rm $dhcp_file
@@ -90,6 +98,11 @@ start_ap(){
     type dnsmasq >/dev/null 2>&1 || { echo >&2 "Error: dnsmasq is required."; exit 1; }
     type iptables >/dev/null 2>&1 || { echo >&2 "Error: iptables is required."; exit 1; }
     set_managed_mode
+    if [ $arg2 ]
+    then
+        ssid=$arg2
+        read -p "enter passphrase: " wpa2_passphrase
+    fi
     cat > $ap_file << AP_CONF
 # temporary hostap config file of qw
 interface=$wlan_iface
@@ -109,19 +122,26 @@ interface=$wlan_iface
 dhcp-range=interface:$wlan_iface,10.113.119.20,10.113.119.60,infinite 
 DHCP_CONF
 
-    echo 1 > /proc/sys/net/ipv4/ip_forward
-    iptables -t nat -A POSTROUTING -o $out_iface -j MASQUERADE
+
+    if [ $out_iface ] && [ $wlan_iface != $out_iface ]
+    then
+        echo 1 > /proc/sys/net/ipv4/ip_forward
+        iptables -t nat -A POSTROUTING -o $out_iface -j MASQUERADE
+    else
+        echo "Warning: Forwarding and NAT won't be enabled."
+    fi
+
     ip a a 10.113.119.1/24 dev $wlan_iface
 
     trap 'stop_ap' SIGINT
-    dnsmasq -C $dhcp_file
+    dnsmasq -C $dhcp_file -x $dhcp_pidfile
     hostapd $ap_file
 }
 
 
 
 disconnect(){
-    killall dhclient
+    kill `cat $dhclient_pidfile`
     rm $wpa_file
 }
 
@@ -131,9 +151,14 @@ connect_to_ap(){
     type wpa_supplicant >/dev/null 2>&1 || { echo >&2 "Error: wpa_supplicant is required."; exit 1; }
     type dhclient >/dev/null 2>&1 || { echo >&2 "Error: dhclient is required."; exit 1; }
     set_managed_mode
+    if [ $arg2 ]
+    then
+        ssid=$arg2
+        read -p "enter passphrase: " wpa2_passphrase
+    fi
     trap 'disconnect' SIGINT
     wpa_passphrase $ssid $wpa2_passphrase > $wpa_file
-    dhclient $wlan_iface &
+    dhclient $wlan_iface -pf $dhclient_pidfile &
     wpa_supplicant -i $wlan_iface -c $wpa_file
 }
 
@@ -166,7 +191,13 @@ fi
 old_forward_value=`cat /proc/sys/net/ipv4/ip_forward`
 
 # find available wlan interfaces and prompt user if multiple are found
-wlan_iface=`iw dev | grep phy -A1 | grep Interface | cut -d " " -f 2`
+wlan_iface=`iw dev | grep Interface | cut -d " " -f 2`
+if [ -z $wlan_iface ]
+then
+    echo "Error: no wlan interface found"
+    exit 1
+fi
+
 if [ `echo "$wlan_iface" | wc -l` -gt 1 ]
 then
     echo "multiple wlan interfaces found:"
@@ -178,16 +209,17 @@ fi
 # find interface of default route
 out_iface=`ip route | grep -e 'default.*via' -e '0.0.0.0.*via' | head -n 1 | cut -d " " -f 5`
 
-if [ "$wlan_iface" = "$out_iface" ]
+if [ -z "$out_iface" ]
 then
-    echo "Warning: the default route is using the selected wlan interface"
+    echo "Warning: no interface for default route found."
+elif [ $wlan_iface = $out_iface ]
+then
+    echo "Warning: the default route is using the selected wlan interface."
 fi
 
 if [ $# -gt 1 ]
 then
-channel=" -c $2"
-else
-channel=""
+arg2=$2
 fi
 
 type ip >/dev/null 2>&1 || { echo >&2 "Error: ip is required."; exit 1; }
@@ -198,8 +230,7 @@ case $1 in
     "c"|"connect")      connect_to_ap;;
     "s"|"sniff")        set_monitor_mode;;
     "m"|"managed")      set_managed_mode;;
-    "u"|"up")           set_interface_up;;
-    "d"|"down")         set_interface_down;;
+    "k"|"kill")         kill_all;;
     "r"|"random")       set_random_mac;;
     "p"|"permanent")    set_permanent_mac;;
     *)                  print_usage;;
